### ISSUE TITLE
Create payment method

### ISSUE THREAD

**Issue by hectopascal** [CSCI-GA-2820-SP24-003/payments#1]
**As a** user
**I need** to add payment methods to my account  
**So that** I can make a purchase.
   
 ### Details and Assumptions
 * Multiple payment methods can be added to 1 user
 * Payment method is stored to database
 * Payment method resource is added to the `payment_methods` table and is of the following form:
```
payment_method:
  id: string
  payment_type: 'credit_card' | 'paypal'
  payment_type_id: string (foreign key)
  display_name: string
  user_id: string
```
if the `payment_type == 'credit_card'`, then a `credit_card` resource in `credit_cards` table is created:
```
credit_card:
  id: string
  payment_method_id: string (foreign key)
  first_name: string
  last_name: string
  card_number: string
  expiry_month: string
  expiry_year: string
  security_code: string
  billing_address: string
  zip_code: string
```
similarly, if the `payment_type == 'paypal'`, then a `paypal` resource in `paypals` table is created:
```
paypal:
  id: string
  payment_method_id: string (foreign key)
  email: string
```

   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the user has details of a payment method
 When they submit a form to create payment method
 Then the payment method is linked to the user account and can be selected to use.

 Given a payments service consumer
 When they POST to `/payment-method` with a body that contains correct fields: 
 `display_name` (string),
 `payment_type` is `credit_card` (enum: `credit_card` | `paypal`),
 `first_name` (string),
 `last_name` (string),
 `card_number` (16 digit string, numbers only),
 `expiry_date` (string format "mm/dd"),
 `security_code` (string, 3 numeric characters),
 `billing_address` (string),
 `zip_code` (string, 5 numbers only),
 `user_id` (string)
 Then the payment method resource is created and the endpoint returns the newly created payment method resource with status 201 (created resource)

Given a payment service consumer
When they POST to `/payment-method` with a body that contains correct fields:
 `display_name` (string),
 `payment_type` is `paypal` (enum: `credit_card` | `paypal`),
 `email` (string, email)
Then the payment method resource is created and the endpoint returns the newly created payment method resource with status 201 (created resource)
```
