### ISSUE TITLE
Create `CreditCard` model

### ISSUE THREAD

**Issue by nedjulius** [CSCI-GA-2820-SP24-003/payments#18]
**As a** developer
**I need** model for `Credit Card` resource
**So that** I can link newly created payment method with a Credit Card resource
   
 ### Details and Assumptions
 * It will be used with `PaymentMethod` resource and will have one-to-one relationship
 * Resource will look like this:
```
credit_card:
  id: int
  payment_method_id: int (foreign key)
  first_name: string
  last_name: string
  card_number: string
  expiry_month: string
  expiry_year: string
  security_code: string
  billing_address: string
  zip_code: string
```
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a database
When a request is sent for create a payment method with credit card method type
Then a credit card entry is created
```
