### ISSUE TITLE
Create `PaymentMethod` resource

### ISSUE THREAD

**Issue by hectopascal** [CSCI-GA-2820-SP24-003/payments#8]
**As a**  sys admin
**I need** a database
**So that** I can store payment methods  
   
 ### Details and Assumptions
 * postgresql database
```
payment_method:
  id: int
  payment_type: 'credit_card' | 'paypal'
  payment_type_id: string (foreign key)
  display_name: string
  user_id: string
```
if the `payment_type == 'credit_card'`, then a `credit_card` resource in `credit_cards` table is created:
```
credit_card:
  id: int
  payment_method_id: int (foreign key)
  first_name: string
  last_name: string
  card_number: string
  expiry_month: string
  expiry_year: string
  security_code: string
  billing_address: string
  zip_code: string
```
 ### Acceptance Criteria  
   
 ```gherkin
 Given a database
 When a request is sent for create/read/update/delete
 Then data is correctly modified
```
